-- ====================================================================
-- SISTEMA DE RECOMENDACIÓN DE MÚSICA HÍBRIDO (BeatMatch AI)
-- MODELO ENTIDAD-RELACIÓN COMPLETO PARA SUPABASE (POSTGRESQL)
-- ====================================================================

-- 1. TABLA DE USUARIOS (users)
-- Almacena perfiles de usuarios reales y perfiles de arquetipos sintéticos
CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,                             -- ej: 'real_samuel', 'user_0001'
    username TEXT UNIQUE NOT NULL,                  -- ej: 'samuel' (normalizado)
    display_name TEXT,                              -- ej: 'Samuel Pérez'
    email TEXT,                                     -- opcional
    is_synthetic BOOLEAN DEFAULT false,             -- false para personas reales
    archetype TEXT DEFAULT 'real_user',             -- 'real_user', 'genre_fan', 'eclectic', etc.
    favorite_genres TEXT[],                         -- array de géneros favoritos ej: {'rock', 'pop'}
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    last_active_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. TABLA DE CATÁLOGO DE CANCIONES (tracks)
-- Almacena metadatos y vectores acústicos de Spotify (81,207 canciones)
CREATE TABLE IF NOT EXISTS tracks (
    track_id TEXT PRIMARY KEY,                      -- ID oficial de Spotify
    track_name TEXT NOT NULL,
    artists TEXT NOT NULL,
    album_name TEXT,
    track_genre TEXT,
    popularity INTEGER DEFAULT 0,
    duration_ms INTEGER,
    explicit BOOLEAN DEFAULT false,
    danceability FLOAT,
    energy FLOAT,
    key INTEGER,
    loudness FLOAT,
    mode INTEGER,
    speechiness FLOAT,
    acousticness FLOAT,
    instrumentalness FLOAT,
    liveness FLOAT,
    valence FLOAT,
    tempo FLOAT,
    time_signature INTEGER,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. TABLA CENTRAL DE INTERACCIONES / CALIFICACIONES (user_interactions)
-- Tabla de hechos para el Filtrado Colaborativo (SVD)
CREATE TABLE IF NOT EXISTS user_interactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,                          -- ID del usuario
    track_id TEXT NOT NULL,                         -- ID de la canción
    rating FLOAT NOT NULL CHECK (rating >= 0.5 AND rating <= 5.0), -- 5.0 (Like) / 1.0 (Dislike)
    archetype TEXT DEFAULT 'real_user',
    interaction_type TEXT DEFAULT 'like',           -- 'like', 'dislike', 'play', 'skip'
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT uq_user_track UNIQUE (user_id, track_id)
);

-- 4. TABLA DE AUDITORÍA DE RECOMENDACIONES (recommendation_history)
-- Registra qué recomendó el motor, con qué peso alpha y cómo fue evaluado
CREATE TABLE IF NOT EXISTS recommendation_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    seed_track_id TEXT,                             -- Canción consultada como semilla
    recommended_track_id TEXT NOT NULL,             -- Canción sugerida
    rank_position INTEGER DEFAULT 1,                -- Posición #1, #2, ...
    alpha_weight FLOAT DEFAULT 0.5,                 -- Balance híbrido usado [0, 1]
    content_score FLOAT,                            -- Score de similitud acústica
    collab_score FLOAT,                             -- Score predicho por SVD
    hybrid_score FLOAT,                             -- Score combinado final
    source TEXT DEFAULT 'hybrid',                   -- 'content', 'collab', 'hybrid'
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. TABLA DE CONVERSACIONES CON EL DJ VIRTUAL (dj_chat_logs)
-- Registra las consultas en lenguaje natural a BeatBot AI
CREATE TABLE IF NOT EXISTS dj_chat_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT,
    prompt TEXT NOT NULL,                           -- ej: 'música para entrenar en el gym'
    mood_detected TEXT,                             -- ej: 'entrenar', 'relax', 'triste'
    bot_response TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ====================================================================
-- ÍNDICES DE RENDIMIENTO (Performance Indexes)
-- ====================================================================
CREATE INDEX IF NOT EXISTS idx_interactions_user_id ON user_interactions(user_id);
CREATE INDEX IF NOT EXISTS idx_interactions_track_id ON user_interactions(track_id);
CREATE INDEX IF NOT EXISTS idx_interactions_archetype ON user_interactions(archetype);
CREATE INDEX IF NOT EXISTS idx_tracks_genre ON tracks(track_genre);
CREATE INDEX IF NOT EXISTS idx_tracks_popularity ON tracks(popularity DESC);
CREATE INDEX IF NOT EXISTS idx_rec_history_user ON recommendation_history(user_id);

-- ====================================================================
-- SEGURIDAD ROW LEVEL SECURITY (RLS)
-- Permite lectura y escritura transparente para la aplicación
-- ====================================================================
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permitir todo en users" ON users;
CREATE POLICY "Permitir todo en users" ON users FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE tracks ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permitir todo en tracks" ON tracks;
CREATE POLICY "Permitir todo en tracks" ON tracks FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE user_interactions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permitir lectura publica" ON user_interactions;
DROP POLICY IF EXISTS "Permitir insercion y actualizacion publica" ON user_interactions;
CREATE POLICY "Permitir todo en user_interactions" ON user_interactions FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE recommendation_history ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permitir todo en recommendation_history" ON recommendation_history;
CREATE POLICY "Permitir todo en recommendation_history" ON recommendation_history FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE dj_chat_logs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permitir todo en dj_chat_logs" ON dj_chat_logs;
CREATE POLICY "Permitir todo en dj_chat_logs" ON dj_chat_logs FOR ALL USING (true) WITH CHECK (true);
